account/urls.py
from django.urls import path
from account import views

app_name = "account"

urlpatterns = [

    path('employee/register/', views.employee_registration, name='employee-registration'),
    path('employer/register/', views.employer_registration, name='employer-registration'),
    path('profile/edit/<int:id>/', views.employee_edit_profile, name='edit-profile'),
    path('login/', views.user_logIn, name='login'),
    path('logout/', views.user_logOut, name='logout'),
]

job/urls.py
from django.contrib import admin
from django.urls import path , include
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobapp.urls')),
    path('', include('account.urls')),

]

jobapp/urls.py
from django.urls import path
from jobapp import views

app_name = "jobapp"


urlpatterns = [

    path('', views.home_view, name='home'),
    path('jobs/', views.job_list_View, name='job-list'),
    path('job/create/', views.create_job_View, name='create-job'),
    path('job/<int:id>/', views.single_job_view, name='single-job'),
    path('apply-job/<int:id>/', views.apply_job_view, name='apply-job'),
    path('bookmark-job/<int:id>/', views.job_bookmark_view, name='bookmark-job'),
    path('about/', views.single_job_view, name='about'),
    path('contact/', views.single_job_view, name='contact'),
    path('result/', views.search_result_view, name='search_result'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('dashboard/employer/job/<int:id>/applicants/', views.all_applicants_view, name='applicants'),
    path('dashboard/employer/job/edit/<int:id>', views.job_edit_view, name='edit-job'),
    path('dashboard/employer/applicant/<int:id>/', views.applicant_details_view, name='applicant-details'),
    path('dashboard/employer/close/<int:id>/', views.make_complete_job_view, name='complete'),
    path('dashboard/employer/delete/<int:id>/', views.delete_job_view, name='delete'),
    path('dashboard/employee/delete-bookmark/<int:id>/', views.delete_bookmark_view, name='delete-bookmark'),


]

templates/base.html
<!DOCTYPE html>
<html>
      {% include 'head.html' %}
      <body id="top">
            {% include 'header.html' %}
            {% block content %}{% endblock %}
            {% include 'footer.html' %}
            {% include 'scripts.html' %} 
            {% block extra_scripts %} {% endblock %}
      </body>
</html>

templates/footer.html
    <footer class="site-footer">

      <a href="#top" class="smoothscroll scroll-top">
        <span class="icon-keyboard_arrow_up"></span>
      </a>

      <div class="container">
        <div class="row mb-5">
          <div class="col-6 col-md-3 mb-4 mb-md-0">
            <h3>Category</h3>
            <ul class="list-unstyled">
              <li><a href="#">Web Developers</a></li>
              <li><a href="#">Python</a></li>
            </ul>
          </div>
          <div class="col-6 col-md-3 mb-4 mb-md-0">
            <h3>Company</h3>
            <ul class="list-unstyled">
              <li><a href="#">About Us</a></li>
              <li><a href="#">Blog</a></li>
            </ul>
          </div>
          <div class="col-6 col-md-3 mb-4 mb-md-0">
            <h3>Support</h3>
            <ul class="list-unstyled">
              <li><a href="#">Support</a></li>
              <li><a href="#">Terms of Service</a></li>
            </ul>
          </div>
          <div class="col-6 col-md-3 mb-4 mb-md-0">
            <h3>Contact Us</h3>
          </div>
        </div>

        <div class="row text-center">
          <div class="col-12">
            <p class="copyright"><small>
            Copyright &copy; <a>Job Finder</a></small></p>
          </div>
        </div>
      </div>
    </footer>
  
  </div>

templates/head.html
{% load static %}

<head>
    <title>Job Finder &mdash; Find Your Job</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}" />
    <link rel="stylesheet" href="{% static 'css/custom-bs.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-select.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/line-icons/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

templates/header.html
<div id="overlayer"></div>
<div class="loader">
  <div class="spinner-border text-primary" role="status">
    <span class="sr-only">Loading...</span>
  </div>
</div>


<div class="site-wrap">

  <div class="site-mobile-menu site-navbar-target">
    <div class="site-mobile-menu-header">
      <div class="site-mobile-menu-close mt-3">
        <span class="icon-close2 js-menu-toggle"></span>
      </div>
    </div>
    <div class="site-mobile-menu-body"></div>
  </div> <!-- .site-mobile-menu -->


  <!-- NAVBAR -->
  <header class="site-navbar mt-3">
    <div class="container-fluid">
      <div class="row align-items-center">
        <div class="site-logo col-6"><a href="{% url 'jobapp:home' %}">Job Finder</a></div>
        <nav class="mx-auto site-navigation">
          <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">
            <li><a href="{% url 'jobapp:home' %}" class="nav-link">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="{% url 'jobapp:job-list' %}">Job Listings</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
        </nav>
        <div class="right-cta-menu text-right d-flex aligin-items-center col-6">
          <div class="ml-auto">
            <div class="site-navigation fix">
              <ul class="site-menu js-clone-nav d-none d-xl-block ml-0 pl-0">

                {% if user.is_authenticated and user.role == 'employer'  %}
                <a href="{% url 'jobapp:create-job' %}"
                  class="js-clone-nav pr-3 btn btn-outline-white border-width-2 d-none d-lg-inline-block"><span
                    class="mr-2 icon-add"></span>Publish Job</a>

                  
                    <li class="pr-3 has-children">
                      <a>Dashboard</a> 
                      <ul class="dropdown">
                        <li><a href="{% url 'jobapp:dashboard' %}">Dashboard</a></li>
                        <li><a href="{% url 'account:logout' %}">Logout</a></li>
                      </ul>
                    </li>

                {% elif user.is_authenticated %}

                <li class="pr-3 has-children">
                  <a>Profile</a>
                  <ul class="dropdown">
                    <li><a href="{% url 'account:edit-profile' request.user.id %}">Edit Settings</a></li>
                  </ul>
                </li>

                <li class="pr-3">
                  <a href="{% url 'jobapp:dashboard' %}">Dashboard</a>
                </li>
                <a href="{% url 'account:logout' %}"
                class="btn btn-primary border-width-2 d-none d-lg-inline-block"><span
                  class="mr-2 icon-lock_outline"></span>Log Out</a>
                {% else %}

                <li class="pr-3 has-children">
                  <a>Register</a>
                  <ul class="dropdown">
                    <li><a href="{% url 'account:employer-registration' %}">Employer</a></li>
                    <li><a href="{% url 'account:employee-registration' %}">Employee</a></li>
                  </ul>
                </li>

                <a href="{% url 'account:login' %}"
                  class="js-clone-nav btn btn-primary border-width-2 d-none d-lg-inline-block ov-fix"><span
                    class="mr-2 icon-lock_outline"></span>Log In</a>
                {% endif %}
              </ul>
            </div>

        <a href="#" class="site-menu-toggle js-menu-toggle d-inline-block d-xl-none mt-lg-2 ml-3"><span
            class="icon-menu h3 m-0 p-0 mt-2"></span></a>
      </div>
    </div>
  </header>

templates/messages.html
{% if messages %}
{% for message in messages %}
  <div class="mb-5 alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}
{% endif %}

templates/scripts.html
{% load static %} 
    <!-- SCRIPTS -->

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'js/stickyfill.min.js' %}"></script>
    <script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
    <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'js/bootstrap-select.min.js' %}"></script>
    <script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script> 
 
    <script src="{% static 'js/custom.js' %}"></script> 